fx_version "adamant"

game "gta5"

this_is_a_map "yes"

data_file "DLC_ITYP_REQUEST" "stream/h4_mph4_terrain_metadata_004.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_mph4_terrain_metadata_001.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_mph4_terrain_metadata_003_strm.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_mph4_terrain_metadata_002.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_mph4_terrain_metadata_005.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_mph4_terrain_lod.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_mph4_terrain_metadata_001_strm.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_mph4_terrain_metadata_003.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_mph4_terrain_metadata_006.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_mph4_terrain_metadata_002_strm.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_int_mp_h_props.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_int_mp_doors.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_mp_apa_yacht_jacuzzi.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_mp_apa_yacht.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_props_h4_mines.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_props_sub_int_h4.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_prop_h4_accs_01.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_prop_h4_accs_02.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_prop_h4_casino.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_prop_h4_coke_01.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_prop_h4_des_gate.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_prop_h4_des_gate_end.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_prop_h4_dj.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_prop_h4_ground_cover.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_prop_h4_hatches_01.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_prop_h4_island_01.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_prop_h4_island_02.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_prop_h4_island_03.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_prop_h4_lights.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_prop_h4_lights_02.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_prop_h4_lights_03.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_prop_h4_lights_04.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_prop_h4_lights_05.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_prop_h4_lights_content.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_prop_h4_money_01.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_prop_h4_office_01.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_prop_h4_potted.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_prop_h4_rock.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_prop_h4_sam.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_prop_h4_sub.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_prop_h4_tables.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_prop_h4_trees.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_prop_h4_weed_01.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_yacht_metadata_001_strm.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_yacht_metadata_001.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_mph4_island_combine_metadata_002.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_mph4_island_combine_metadata_009.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_mph4_airstrip_interior_0_airstrip_hanger.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_mph4_island_combine_metadata_003_strm.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_mph4_island_combine_metadata_007.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_mph4_island_combine_metadata_001_strm.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_mph4_island_combine_metadata_005_strm.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_mph4_island_combine_metadata_003.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_mph4_island_combine_metadata_010.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_mph4_island_combine_metadata_002_strm.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_mph4_island_combine_metadata_006.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_mph4_island_combine_metadata_004.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_mph4_island_combine_metadata_005.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_mph4_island_combine_metadata_008.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_mph4_island_combine_metadata_001.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_mph4_island_lod.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_mph4_island_combine_metadata_011.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_mph4_island_combine_metadata_004_strm.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_mph4_island_strm.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_mph4_island.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_dlc_int_01_h4.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_dlc_int_02_h4.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_int_mp_yacht.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_dlc_int_05_h4.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_dlc_int_04_h4.ytyp"
data_file "DLC_ITYP_REQUEST" "stream/h4_dlc_int_03_h4.ytyp"

data_file "GTXD_PARENTING_DATA" "client/mph4_gtxd.meta"

data_file "SCALEFORM_DLC_FILE" "stream/int3232302352.gfx"

files {
	"client/mph4_gtxd.meta",
	"stream/int3232302352.gfx",
}

client_scripts {
	"@PolyZone/client.lua",
	"@PolyZone/BoxZone.lua",
    "client/client.lua",
	"client/main.lua",
}